### ISSUE TITLE
todo before Josh v2

### ISSUE THREAD

**Issue by RealShadowNova** [josh-development/core#58]
- [ ] Add unit tests for [`Josh`](https://github.com/josh-development/core/blob/main/src/lib/structures/Josh.ts)
- [ ] Add documentation for [`JoshProvider`](https://github.com/josh-development/core/blob/main/src/lib/structures/JoshProvider.ts) methods
- [x] Refactor the key-path system to better replicate Enmap (@RealShadowNova) #62
- [x] Add an [`Array#forEach()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) like method #60
- [ ] Move and rewrite provider tests to `@joshdb/tests` (@WilsontheWolf)
- [ ] Refactor `@joshdb/mongo` to use `mongodb` rather then `mongoose` (@dan-online)
- [ ] Move [`AutoEnsure`](https://github.com/josh-development/core/blob/main/src/middlewares/AutoEnsure.ts) to `@joshdb/auto-ensure`
- [ ] Add provider migrations (@RealShadowNova) #63
- [ ] Add `@joshdb/sqlite` (@eslachance)
- [ ] Rewrite [josh-development/website](https://github.com/josh-development/website)

**Comment by thetayloredman** [comment]
#60 handles each()

**Comment by RealShadowNova** [comment]
Closing this issue in favor of Projects
